openapi: 3.0.0
info:
  title: Code Improve API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0

servers: #These servers will be displayed on the UI
  - url: http://localhost:3000/
    description: Local server
  - url: https://prod.com/
    description: Pre Production server
  - url: https://test.com/
    description: Production server

components: #This components will be used to display schemas on the UI
  securitySchemes:
    ApiToken: # arbitrary name for the security scheme
      type: http #This can be http/apikey
      scheme: basic #this can be basic/bearer. It will display username/password if basic, if bearer then token field will be displayed

    ApiKey: # arbitrary name for the security scheme
      type: apiKey
      in: header # can be "header", "query" or "cookie". This value is fetched from header
      name: apikey

paths:
  /users/detail/{userId}:
    get:
      security: #This will enable authorize button on the UI and enables authentication
        - ApiToken: [] #When post request on this URL, it requires both authentications
        - ApiKey: []
      summary: Returns a user details by ID.
      parameters:
        - name: userId
          in: path #This value is fetched from URL path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            # type : integer
            # format: int64
            type: string
            example: "Users String" #This is place holder
            minimum: 1
      responses:
        "200":
          description: OK

  paths:
  /users/list:
    post:
      tags: #this is used to create tags for the API
        - User List API
      summary: Returns a user list.
      description: This is to create users

      parameters:
        - in: query #This is like a query parameter in the URL
          name: month_year
          schema:
            #type: integer
            example: 2022-10
      requestBody:
        required: true
        content:
          multipart/form-data: #either of json data or form data can be selected
            #application/json:
            schema:
              type: object
              properties:
                page_no:
                  type: integer
                  example: 1
                type:
                  type: string
                  example: "A"
                status:
                  type: integer
                  example: 0
                fileName:
                  type: string
                  format: binary

      responses:
        "200":
          description: A user object.
        "400":
          description: The specified user ID is invalid (not a number).
        "404":
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
